### ISSUE TITLE
Problem with special characters in the German alphabet. 

### ISSUE THREAD

**Issue by AsgardAGI** [lukaszliniewicz/Pandrator#1]
Hello, first of all great project, thanks for it and your work. There is only one problem, if you want to generate something in German, no special characters / umlauts (äöü) are taken over in German. 

Thank you very much.

**Comment by lukaszliniewicz** [comment]
Sorry, it seems that "Remove diacritics" is enabled by default (I was having trouble with transliterated Japanese and special characters, and I must have left it enabled by defult). Please go to "Text processing" and disable "Remove diacritics".
