### ISSUE TITLE
Cannot install  NISQA fastapi because of old librosa output

### ISSUE THREAD

**Issue by yodatak** [lukaszliniewicz/Pandrator#11]
Hi thanks again 
NISQA is unmaintend for long time and this PR could be interesting to help to install on modern python
https://github.com/gabrielmittag/NISQA/pull/47

Like 
https://librosa.org/doc/latest/changelog.html

Librosa output is removed since 2020

i got this error
https://github.com/librosa/librosa/issues/774

Did we want to make container of this fastapi ?

**Comment by yodatak** [comment]
Maybe using something like LocalAI https://github.com/mudler/LocalAI?tab=readme-ov-file

**Comment by lukaszliniewicz** [comment]
I made a very simple FastAPI implementation of NISQA: https://github.com/lukaszliniewicz/NISQA-API. It should work if you follow the conda instructions. I'm still not sure how useful it is to improve results, though.
