### ISSUE TITLE
Getting RVC to work

### ISSUE THREAD

**Issue by Airmiz** [lukaszliniewicz/Pandrator#13]
When I generate it runs and completes, but no sentences or audio is output.

Steps on how to get RVC working?
thanks,

**Comment by lukaszliniewicz** [comment]
Does it generate audio without RVC? To get RVC, you need to install RVC_CLI (https://github.com/blaise-tk/RVC_CLI). There are instructions in its repository.

**Comment by Airmiz** [comment]
right, I have the pth and index, it just crashes every time I attempt.

**Comment by lukaszliniewicz** [comment]
An you have installed RVC_CLI? Does it crash without RVC? How have you installed Pandrator, with the installer?

**Comment by Airmiz** [comment]
Correct, Pandrator base running and work. What do you mean by RVC_CLI running?

**Comment by lukaszliniewicz** [comment]
Just if you can start it and if it's running alongside Pandrator.

**Comment by lukaszliniewicz** [comment]
From their documentation:

```
Windows
Execute the [install.bat](https://github.com/blaise-tk/RVC_CLI/blob/main/install.bat) file to activate a Conda environment. Afterward, launch the application using env/python.exe main.py instead of the conventional python main.py command.
```

If you cloned the repository into, say, C:/AI, then run the install.bat from there, you would open Windows Terminal in that folder (right click and select the option to open the terminal) and run env/python.exe main.py.

**Comment by lukaszliniewicz** [comment]
Sorry, the actual command is `env/python.exe main.py api`.

**Comment by Airmiz** [comment]
This what I get running the generation with the API open

INFO:     Started server process [12960]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:52083 - "POST /infer HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application

**Comment by cif232** [comment]
I ran into (what I think is the same issue) but was able to resolve it by making the change in this comment:
https://github.com/blaise-tk/RVC_CLI/issues/31#issue-2165599980

to the api.py file from RVC_CLI .

**Comment by Airmiz** [comment]
That fix the API error, now it just isn't generating any sentences/wav files.

**Comment by Airmiz** [comment]
using VoiceCraft if that is any help
