### ISSUE TITLE
urllib3.connection. HTTPConnection

### ISSUE THREAD

**Issue by cosanostratr** [lukaszliniewicz/Pandrator#18]
![Ekran Görüntüsü (9)](https://github.com/lukaszliniewicz/Pandrator/assets/147934552/af122cf5-8627-4d5d-812c-a960e2410c4d)
Failed to connect to the local server: 
HTTPConnectionPool(host="localhost', port=8020): Maximum retries 
exceeded with url: /speakers list (Cause 
NewConnection€rrort'<urllib3.connection. HTTPConnection object 
0x000001C549E54880>: Failed to establish a new connection: 
[Win€rror 10061] Because the target machine actively rejected 
the connection cannot be established))

i try localhost change 0.0.0.0 and firewall unblock. but not work

**Comment by lukaszliniewicz** [comment]
Is the server running, can you access http://127.0.0.1:8020/docs in your browser?

**Comment by cosanostratr** [comment]
i can't

**Comment by razvanab** [comment]
Same here. Some help, please.

**Comment by lukaszliniewicz** [comment]
Please make sure that the server is running. I've updated the automatic Windows installer today. If you don't use it, install and launch XTTS API Server manually.
