### ISSUE TITLE
Apple silicon support?

### ISSUE THREAD

**Issue by Excurl** [lukaszliniewicz/Pandrator#2]
Does it support mac mps?
Can you do a demo in huggingface?

**Comment by lukaszliniewicz** [comment]
Please check Mac support of the TTS engines/APIs, Pandrator itself is
simply a Python app and it will run on any system. It uses tkinter for its
GUI, not gradio, and it uses other services (servers running locally) to
generate speech, so at the moment I can't really make a demo. But you will
find demos of the TTS models it uses easily enough, I think.

Op vr 5 apr. 2024 05:01 schreef Excurl ***@***.***>:
