### ISSUE TITLE
How to install the VoiceCraft API Server?

### ISSUE THREAD

**Issue by SoftologyPro** [lukaszliniewicz/Pandrator#20]
XTTS is an easy install with
`pip install xtts-api-server`
and then start the server with
`python -m xtts_api_server`

Silero is also an easy install with
`pip install silero-api-server`
and then run it with
`python -m silero_api_server`

VoiceCraft does not seem to be that simple?  Do you have a set of steps to install and start the server ready for use with Pandrator?  Thanks.

**Comment by lukaszliniewicz** [comment]
Please look here for instructions: https://github.com/lukaszliniewicz/VoiceCraft_API. There is an executable to install and run the server.
