### ISSUE TITLE
processing problem

### ISSUE THREAD

**Issue by andre9845** [lukaszliniewicz/Pandrator#28]
I have a question is it normal when I make a voiceover for a movie at the beginning it goes fast processing so after 150 lines it starts to slow down I do not know if it is the fault of the program or the server,how it can be fixed I would appreciate it,and one more thing LLM I can not select the model I have filed to connect the llm api and evaluation probably does not work long processing,if I misunderstood something please correct me.

**Comment by lukaszliniewicz** [comment]
I haven't had the issue with generation slowing down after some time. Is GPU utilisation constant? Isn't the GPU throttling down due to overheating, perhaps? What hardware are you running it on? 

Does Text Generation WebUI work correctly? Are you able to load the models?

**Comment by andre9845** [comment]
I have an RTX 3060 Ti 8GB card, a new guide on how to use the program would be useful, maybe I'm doing something wrong, in the gui I have the low v ram mode and use deepspeed selected

**Comment by lukaszliniewicz** [comment]
Try unselecting lowvram. Can you use Text Generation WebUI on its own?

**Comment by andre9845** [comment]
I have version 0.9, I have unchecked low ram and deepspeed, it works a little slower but more stable.
