### ISSUE TITLE
Add synchronised audio to video file doesn't work for me. 

### ISSUE THREAD

**Issue by AsgardAGI** [lukaszliniewicz/Pandrator#3]
I'm thrilled, it works really well! Add synchronised audio to video file doesn't work for me I don't know maybe it's the video codec? No audio file is extracted. And the dubbing from .srt subtitle files is very slow. For a 60min video it takes 3+ hours with XTTS. But still better than having to do it manually. Regards really great work.

**Comment by lukaszliniewicz** [comment]
I'm sorry to hear it doesn't work, I will check if I haven't broken something recently. Can you please tell me what video container, audio and video codec the video file you tried had?

**Comment by AsgardAGI** [comment]
YouTube video downloaded with the JDownloader. MP4 format. I have an RTX4090 so it can't be the GPU. But what I have to say, I'm using a fine-tuned 0.2.2 model. The interface(client) is also laggy(delayed). I have not tried normal TXT generation now. 

https://github.com/lukaszliniewicz/Pandrator/assets/164924910/34d8e5c1-c50c-4e65-a1bb-3c9379a8ed8b

**Comment by lukaszliniewicz** [comment]
Did the file have the .mp4 or .webm extension? Are you on Linux or Windows?

**Comment by AsgardAGI** [comment]
Windows11 and it is an mp4. I have found the "bug", I have to activate Add synchronised audio to video file.  But I can't extract an audio file from a video, not even from other videos. 

https://github.com/lukaszliniewicz/Pandrator/assets/164924910/f0c5c4b4-ac7b-4c80-888c-b98d97fa20a8

**Comment by lukaszliniewicz** [comment]
I think I may know what has gone wrong. I included "ffmpeg" instead of "ffmpeg-python" in the requirements. Could you please do `pip install ffmpeg-python` or `conda\Scripts\conda.exe run -n pandrator_installer pip install ffmpeg-python` from inside the Pandrator folder if you used the installation script?

**Comment by lukaszliniewicz** [comment]
PS. If you decide to update the conda env, it might be necessary to do `pip uninstall ffmpeg` before installing ffmpeg-python.

**Comment by AsgardAGI** [comment]
pip uninstall ffmpeg-python/pip install ffmpeg-python Did not work, no change. I have now installed your new update. And now everything works. Super thanks.
