### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by steve218812** [lukaszliniewicz/Pandrator#33]
I am getting the following error:
[pandrator_installation_log_20240915_135714.log](https://github.com/user-attachments/files/17005675/pandrator_installation_log_20240915_135714.log)
Traceback (most recent call last):
  File "pandrator_start_minimal_xtts.py", line 267, in <module>
  File "pandrator_start_minimal_xtts.py", line 235, in main
  File "pandrator_start_minimal_xtts.py", line 106, in run_xtts_api_server
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Stefanos\\Downloads\\Pandrator\\xtts-api-server'
I also attached the installation log.

**Comment by lukaszliniewicz** [comment]
It looks like you used an old installation script. Please use the latest one from releases: https://github.com/lukaszliniewicz/Pandrator/releases/tag/v.0.0.9.5  (or from the repo: https://github.com/lukaszliniewicz/Pandrator/blob/main/pandrator_installer_launcher.py).

**Comment by lukaszliniewicz** [comment]
Were you able to get it running?
