### ISSUE TITLE
encoder not found

### ISSUE THREAD

**Issue by vargint** [lukaszliniewicz/Pandrator#35]
tried switching the output to mp3 from Opus, and got an error

<img width="587" alt="mp3 error" src="https://github.com/user-attachments/assets/55a5fe1c-e231-4d20-834a-421c63033556">

**Comment by lukaszliniewicz** [comment]
Have you installed Pandrator using the installer or manually?

**Comment by vargint** [comment]
it was installer

**Comment by lukaszliniewicz** [comment]
Hmm, I don't get that error. Please try installing ffmpeg (go to Terminal and run `winget install Gyan.FFmpeg -y`).

**Comment by vargint** [comment]
I'm in the process of trying to get this working on a new computer, hopefully I won't have this issue there
