### ISSUE TITLE
Installation issue - Visual C++ Build Tools prompt

### ISSUE THREAD

**Issue by haroelim** [lukaszliniewicz/Pandrator#36]
Looking at the log, it seem that the installation of Visual C++ Build Tools expects a Y or N response, however the prompt never appears to the user during the installation, and thus the installation fails

> 2024-09-20 21:52:13,549 - INFO - The `msstore` source requires that you view the following agreements before using.
> 2024-09-20 21:52:13,549 - INFO - Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
> 2024-09-20 21:52:13,549 - INFO - The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").
> 2024-09-20 21:52:13,549 - INFO - 

> **_2024-09-20 21:52:13,549 - INFO - Do you agree to all the source agreements terms?
> 2024-09-20 21:52:13,549 - INFO - [Y] Yes  [N] No: An unexpected error occurred while executing the command:
> 2024-09-20 21:52:13,549 - INFO - 0x8a150042 : Error reading input in prompt_**

> 2024-09-20 21:52:13,565 - ERROR - Failed to install/update Microsoft Visual C++ Build Tools. Return code: 2316632130
> 2024-09-20 21:52:13,565 - INFO - Error during Build Tools installation/update. Check the log for details.

Fortunately, I was able to install the XTTS server by manually installing Visual C++ Build Tools

**Comment by lukaszliniewicz** [comment]
Thanks, I haven't run into this myself, I will look into it.

**Comment by lukaszliniewicz** [comment]
I modified the winget/build tools installation process, and hopefully this won't be a problem now (tried it on a fresh W11 install on a VM and setup completed successfully).
