### ISSUE TITLE
XTTS not coming online

### ISSUE THREAD

**Issue by vargint** [lukaszliniewicz/Pandrator#41]
Install went fine.  But failing to launch. 

(trying to use this on a new machine with a GPU)

Attempt 60/60: xtts server is not online yet. Waiting...
ERROR:root:xtts server failed to come online within the specified attempts.
ERROR:root:XTTS server failed to come online

**Comment by lukaszliniewicz** [comment]
Could you please share the installation log with me? You may also try downloading the full portable package (there is no need to install anything, just unpack it and use the launcher): https://1drv.ms/u/s!AgSiDu9lV3iMnfs7t4q3wr5IZKkKtg?e=efWZq3.

**Comment by vargint** [comment]
I used the portable package, and it's loading.  But for some reason I'm not
able to "upload New Model".  The window to select the file opens, I double
click it, then it closes and opens for the 2nd time.  After I double click
or select+click open, nothing happens,

Also, the drop down that should have the list of models is frozen. The
refresh models seems to do nothing.

I had the same issue with another Asus laptop I was testing, but on Lenovo
worked fine. (I was testing out a few machines)

Much mettā,
Yuriy

**Comment by lukaszliniewicz** [comment]
I think you're talking about RVC now. The package I gave you doesn't contain RVC, please download this one (or use the installer to add it): https://1drv.ms/u/s!AgSiDu9lV3iMnf1N2saDtrt6wreXUg?e=Cortua.
