### ISSUE TITLE
DPI resolution, some suggestions

### ISSUE THREAD

**Issue by JohnF51** [lukaszliniewicz/Pandrator#42]
Hi Lukasz,

Congratulations again perfect work, thank you.
I would like to ask you could you edit pandator.py? And send it to me? I have a problem that when I start Pandator I see everything in one bar (like 400x900), even if I put fullscreen I still only see the bar which I have to scroll, can you split it into two windows in one part settings and in the other part generated text?
Could you make the text editing panel show at least three lines? 
Could you make the text box where the text is generated scrollable both vertically and horizontally?
Could you make the selected line where the text is generated more prominent or in a different color?

Alternatively, what could I change in the code to achieve this.
  I am using a 1920x1080 monitor. Thanks a lot, Great work.

**Comment by lukaszliniewicz** [comment]
Accidentally, I've changed the layout of the UI yesterday : ) Now I have also changed the editing popup window and the highlight color of a selected sentence in the listbox:

![python_xdstOEExcV](https://github.com/user-attachments/assets/08659010-1e3d-4d38-9af2-b3b86c98803e)

**Comment by JohnF51** [comment]
Thank you its greate!
