### ISSUE TITLE
Having issue while using rvc model

### ISSUE THREAD

**Issue by scourgeofgodd** [lukaszliniewicz/Pandrator#43]
Hi, i downloaded one of rvc models (kratos). while i try to use it i get this error: 

2024-10-07 14:23:22,381 [ERROR] RVC Processing Error: 'TTSOptimizerGUI' object has no attribute 'rvc_inference'
2024-10-07 14:23:22,401 [ERROR] FFmpeg exited with a non-zero code: 3199971767

Error output:
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with clang version 19.1.0
  configuration: --prefix=/d/bld/ffmpeg_1727723574466/_h_env/Library --cc=clang.exe --cxx=clang++.exe --nm=llvm-nm --ar=llvm-ar --disable-doc --enable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --ld=lld-link --target-os=win64 --enable-cross-compile --toolchain=msvc --host-cc=clang.exe --extra-libs=ucrt.lib --extra-libs=vcruntime.lib --extra-libs=oldnames.lib --strip=llvm-strip --disable-stripping --host-extralibs= --disable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libopus --pkg-config=/d/bld/ffmpeg_1727723574466/_build_env/Library/bin/pkg-config
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[in#0 @ 000001E8278CDFC0] Error opening input: Invalid data found when processing input
Error opening input file C:\Users\A\AppData\Local\Temp\tmptmpsm632.
Error opening input files: Invalid data found when processing input

**Comment by lukaszliniewicz** [comment]
It seems like RVC Python is not available. Have you installed it through the launcher or downloaded the package that contains it?

**Comment by scourgeofgodd** [comment]
Yeah i did download both from launcher and also package :(

**Comment by lukaszliniewicz** [comment]
Please update Pandrator from the launcher and try again.
