### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by shato20** [lukaszliniewicz/Pandrator#44]
Can someone please help troubelshooting this issue?
i am having it while tring to install Voicecraft.
Argument name was not recognized for the current command: '--accept-source-agreements'
 what i did: tried 3 versions of winget: 1.7,1.8 and 1.9
thanks

**Comment by lukaszliniewicz** [comment]
Could you please copy the last part of the installation log?

**Comment by lukaszliniewicz** [comment]
Thanks, I will update the installer in a moment.

**Comment by shato20** [comment]
Update: running "winget install --id eSpeak-NG.eSpeak-NG -e --accept-source-agreements --accept-package-agreements"
works in Poweshell. maybe a lower/uppercase issue?
now i just don't know how to change that command in the installer

**Comment by lukaszliniewicz** [comment]
Yes, this was the problem, the name of the package wasn't right. If you install it manually, you can probably use VoiceCraft already.

**Comment by shato20** [comment]
please, give a notification as soon as you update de package.
and thanks for your work!

**Comment by lukaszliniewicz** [comment]
I have updated the installer, it should work now. But Voicecraft is a bit of a mess right now, it's very slow and not reliable. The developer hasn't been working on it for the last couple of months and I can't say how useful it will be. I'd recommend going with XTTS and selecting a good reference file or fine-tuning it on ~30m of speech, which you can do in Pandrator now.
