### ISSUE TITLE
train the XTTS model

### ISSUE THREAD

**Issue by jacooooooooool** [lukaszliniewicz/Pandrator#47]
I want to train the XTTS model, last option, I choose a folder with 22050kHz mono audio samples
but the script ((Pandrator\conda\envs\whisperx_installer\lib\site-packages\faster_whisper\transcribe.py")) :causes an error :

File "C:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\site-packages\faster_whisper\transcribe.py", line 133, in __init__
2024-10-12 16:13:32,661 [INFO] XTTS Training: self.model = ctranslate2.models.Whisper(
2024-10-12 16:13:32,661 [INFO] XTTS Training: ValueError: Requested float16 compute type, but the target device or backend does not support efficient float16 computation.

which suggests that for my gforce 1080Ti graphics card WhisperX and Ctranslate should be compiled "float=init8"

I don't know how to do this because each add-on in Pandrator creates its own miniconda environment

how to get to the environments below to be able to install older dependencies so that the learning project works on the Gforce GTX 1080Ti graphics card

whisperx_installer
xtts_api_server_installer

Error 2

XTTS Training: Standard error: C:\Users\Jacek\Downloads\Pandrator\conda\envs\whisperx_installer\lib\inspect.py:869: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0

Please guide me, all other functions work correctly and the graphics card is used

**Comment by lukaszliniewicz** [comment]
Hi Jacek, 

How have you installed Pandrator? Using the installer or the package? In any case, these are the envs:

- pandrator_installer (Pandrator, Python RVC and Subdub)
- whisperx_installer (WhisperX)
- xtts_api_server_installer (XTTS API Server)
- easy_xtts_trainer (Easy XTTS Trainer)

If you want to access them directly and run commands, assuming that you're inside the Pandrator folder where the conda folder is located, run `./conda/Scripts/conda.exe run -n <env_name> <comand>`.  For example:  `./conda/Scripts/conda.exe run -n pandrator_installer pip install x`

**Comment by jacooooooooool** [comment]
Thank you very much for the quick response!!!
standard windows installer
https://github.com/lukaszliniewicz/Pandrator/releases/tag/v.0.25

I'm trying... but I see that some dependencies don't want to work together :(
I have to buy a new card, my 1080Ti has POWER!!! it's no longer supported

**Comment by lukaszliniewicz** [comment]
There may be a way to make it work, or perhaps I screwed something up. I will look into it. What you can do is install easy_xtts_trainer on a VM with a GPU from a service like RunPod or Vast.ai. A 3060 12GB can be had for, I don't know, 15 cents per hour or so, including what they charge for storage. 

![chrome_pESeb1BN7V](https://github.com/user-attachments/assets/791f291b-7ec8-48db-a20b-6c4c3454d9f7)
