### ISSUE TITLE
Cannot run on Fedora 39 and python 3.12

### ISSUE THREAD

**Issue by yodatak** [lukaszliniewicz/Pandrator#5]
Hi thanks for this awsome project i would dream of it 

I cannot run the app because of this error

python3 -m venv panda_env
source panda_env/bin/activate.fish
python3 pandrator.py                                                                                                                                                                                      ⬢ 
pygame 2.5.2 (SDL 2.28.2, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
This plataform is not currently supported, check 'support.txt' file for
            information on how to run this class on other platforms.
Traceback (most recent call last):
  File "/var/home/yodatak/Projets/public/Pandrator/pandrator.py", line 2845, in <module>
    main()     
    ^^^^^^
  File "/var/home/yodatak/Projets/public/Pandrator/pandrator.py", line 2839, in main
    root.iconbitmap("pandrator.ico")
  File "/var/home/yodatak/Projets/public/Pandrator/panda_env/lib64/python3.12/site-packages/customtkinter/windows/ctk_tk.py", line 232, in iconbitmap
    super().wm_iconbitmap(bitmap, default)
  File "/usr/lib64/python3.12/tkinter/__init__.py", line 2155, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "pandrator.ico" not defined

Did i do something wrong ?

thanks again

**Comment by lukaszliniewicz** [comment]
Have you cloned the repository or downloaded pandrator.py? In any case, please try it now, I made a change that should handle the icon error. Please let me know if it works.

**Comment by lukaszliniewicz** [comment]
Has it worked? :)

**Comment by yodatak** [comment]
Hey thanks again it work time to understand how to use your software now ^

Here how i make it works on fedora 39/40

```
git clone https://github.com/lukaszliniewicz/Pandrator.git
cd Pandrator
sudo dnf install python3-tkinter ffmpeg-free
python3 -m venv panda_env
source panda_env/bin/activate.fish
pip install -r requirements.txt
python3 pandrator.py
```

i got this error but it start 
```
python3 pandrator.py
pygame 2.5.2 (SDL 2.28.2, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
This plataform is not currently supported, check 'support.txt' file for
            information on how to run this class on other platforms.
Icon file 'pandrator.ico' not found. Proceeding without setting the window icon.
Error details: bitmap "pandrator.ico" not defined
```
![image](https://github.com/lukaszliniewicz/Pandrator/assets/704477/de0b07e4-dfa4-4a40-b17c-c6c53718bc21)

**Comment by lukaszliniewicz** [comment]
I'm glad it worked, apologies for the problems! Let me know if you encounter any other issues :)
