### ISSUE TITLE
Third Zip Package Download link does not work 

### ISSUE THREAD

**Issue by GoudaCouda** [lukaszliniewicz/Pandrator#52]
The download link brings me to a one drive that doesnt have any files available

**Comment by lukaszliniewicz** [comment]
Hmm, it works for me. You mean the biggest package?

**Comment by GoudaCouda** [comment]
This is what i get when clicking on the download link for the largest package


![image](https://github.com/user-attachments/assets/5b3e92bd-ab51-48d4-bafc-dea8c8db2f1f)

**Comment by lukaszliniewicz** [comment]
I generated the link again. Please try this one: https://1drv.ms/u/s!AgSiDu9lV3iMnoVuGyd8Q_thLlS1nQ?e=vfON94.

**Comment by GoudaCouda** [comment]
Its working now Thanks I also just released you had another link with all 3 in a folder
