### ISSUE TITLE
Adding a .srt and pressing 'Generate dubbing audio' Hangs Pandrator

### ISSUE THREAD

**Issue by luckyluca** [lukaszliniewicz/Pandrator#53]
When loading a .srt and pressing generate dubbing audio, Pandrator hangs without giving any error or message.
I'm attaching the .srt as .txt (please rename it back to .srt)
And the two installation logs

Any idea of what I might be doing wrong?
Thanks
L

P.s.
Do you need to use the installer to launch the program?
Just wondering as it's the only .exe and Pandrator.py doesn't launch by itself.
[MOTIVAZIONALE FITNESS.txt](https://github.com/user-attachments/files/17403018/MOTIVAZIONALE.FITNESS.txt)

[pandrator_installation_log_20241016_200104.log](https://github.com/user-attachments/files/17403025/pandrator_installation_log_20241016_200104.log)
[pandrator_installation_log_20241016_215546.log](https://github.com/user-attachments/files/17403026/pandrator_installation_log_20241016_215546.log)

**Comment by lukaszliniewicz** [comment]
Thanks for the file. It works for me - audio is being generated. Could you please check the logs in `Pandrator/Pandrator/logs`? 

You can launch Pandrator as a Python file from the terminal: `python pandrator.py`. The installer/launcher makes it easier since you can also launch the TTS server. Have you checked the "XTTS" box when launching Pandrator?

![image](https://github.com/user-attachments/assets/379c0ce5-715f-4742-8078-b31d6c4a125e)

**Comment by luckyluca** [comment]
Thanks Lukas, I run the exact selection but it freezes all the time.

I tried several things:
-launching Pandrator from the .exe
-launching Pandrator from python
-Downloading the full 30Gb package and running pandrator.py from there
-Downloading the full 30Gb package and running the exe installer and launching from there
-All of the above with and without xtts server running.

Every single time, no matter what, pressing the generate button hangs the interface.
My guess is an interface problem with Pandrator UI.

`INFO:root:Using session folder: D:\pandrator\Pandrator\Outputs\test8
INFO:root:INFO:root:Using session folder: D:\pandrator\Pandrator\Outputs\test8
2024-10-17 15:48:54,066 [INFO] INFO:root:Using session folder: D:\pandrator\Pandrator\Outputs\test8
INFO:root:Starting subtitle translation and dubbing process
INFO:root:INFO:root:Starting subtitle translation and dubbing process
2024-10-17 15:48:54,069 [INFO] INFO:root:Starting subtitle translation and dubbing process
INFO:root:Input file: D:\pandrator\Pandrator\Outputs\test8\MOTIVAZIONALE FITNESS.srt
INFO:root:INFO:root:Input file: D:\pandrator\Pandrator\Outputs\test8\MOTIVAZIONALE FITNESS.srt
2024-10-17 15:48:54,071 [INFO] INFO:root:Input file: D:\pandrator\Pandrator\Outputs\test8\MOTIVAZIONALE FITNESS.srt
INFO:root:Session folder: D:\pandrator\Pandrator\Outputs\test8
INFO:root:INFO:root:Session folder: D:\pandrator\Pandrator\Outputs\test8
2024-10-17 15:48:54,073 [INFO] INFO:root:Session folder: D:\pandrator\Pandrator\Outputs\test8
INFO:root:Using LLM API: anthropic
INFO:root:INFO:root:Using LLM API: anthropic
2024-10-17 15:48:54,075 [INFO] INFO:root:Using LLM API: anthropic
INFO:root:Using LLM model: claude-3-5-sonnet-20240620
INFO:root:INFO:root:Using LLM model: claude-3-5-sonnet-20240620
2024-10-17 15:48:54,079 [INFO] INFO:root:Using LLM model: claude-3-5-sonnet-20240620
INFO:root:Using input subtitles: D:\pandrator\Pandrator\Outputs\test8\MOTIVAZIONALE FITNESS.srt
INFO:root:INFO:root:Using input subtitles: D:\pandrator\Pandrator\Outputs\test8\MOTIVAZIONALE FITNESS.srt
2024-10-17 15:48:54,082 [INFO] INFO:root:Using input subtitles: D:\pandrator\Pandrator\Outputs\test8\MOTIVAZIONALE FITNESS.srt
INFO:root:Created 42 speech blocks
INFO:root:INFO:root:Created 42 speech blocks
2024-10-17 15:48:54,084 [INFO] INFO:root:Created 42 speech blocks
INFO:root:Speech blocks creation completed. Ending process.
INFO:root:INFO:root:Speech blocks creation completed. Ending process.
2024-10-17 15:48:54,086 [INFO] INFO:root:Speech blocks creation completed. Ending process.
INFO:root:Speech blocks generation completed successfully.
2024-10-17 15:48:54,212 [INFO] Speech blocks generation completed successfully.
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
2024-10-17 15:49:54,596 [DEBUG] STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
2024-10-17 15:49:54,599 [DEBUG] STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
2024-10-17 15:49:54,600 [DEBUG] STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
2024-10-17 15:49:54,601 [DEBUG] STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 14814
2024-10-17 15:49:54,603 [DEBUG] STREAM b'IDAT' 91 14814
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
2024-10-17 15:49:54,605 [DEBUG] STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
2024-10-17 15:49:54,606 [DEBUG] STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
2024-10-17 15:49:54,608 [DEBUG] STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
2024-10-17 15:49:54,609 [DEBUG] STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 14814
2024-10-17 15:49:54,610 [DEBUG] STREAM b'IDAT' 91 14814

`

P.s.
What I'm after is generating a wav audio file from a supplied .srt file.
do I need to supply API keys? What do I need exactly?

**Comment by lukaszliniewicz** [comment]
Please try changing the name of the file such that there is no period in it, e.g. "motivazionale_fitness.srt". 

You only need API keyes if you want to translate subtitles. Otherwise it's not needed.

**Comment by luckyluca** [comment]
It worked, thank you! It's really cool!

Is there a way to burn the subtitles into the video?
Also, is there a way for the audio to be as true as possible to the timing of the original .srt ?

P.s. I'm getting the following error when selecting 'update' in the installer_launcher GUI:
`
ERROR:root:Error executing command: D:\Pandrator\conda\Scripts\conda.exe run -n pandrator_installer pip install -r D:\Pandrator\Pandrator\requirements.txt
ERROR:root:Error message: Command '['D:\\Pandrator\\conda\\Scripts\\conda.exe', 'run', '-n', 'pandrator_installer', 'pip', 'install', '-r', 'D:\\Pandrator\\Pandrator\\requirements.txt']' returned non-zero exit status 1.
ERROR:root:STDOUT:
ERROR:root:STDERR: ERROR conda.cli.main_run:execute(125): `conda run pip install -r D:\Pandrator\Pandrator\requirements.txt` failed. (See above for error)

ERROR:root:Failed to update: Command '['D:\\Pandrator\\conda\\Scripts\\conda.exe', 'run', '-n', 'pandrator_installer', 'pip', 'install', '-r', 'D:\\Pandrator\\Pandrator\\requirements.txt']' returned non-zero exit status 1.
ERROR:root:Traceback (most recent call last):
  File "D:\pandrator_installer.py", line 938, in update_pandrator
    self.run_command(update_cmd, cwd=pandrator_repo_path)
  File "D:\pandrator_installer.py", line 453, in run_command
    raise subprocess.CalledProcessError(process.returncode, command, stdout, stderr)
subprocess.CalledProcessError: Command '['D:\\Pandrator\\conda\\Scripts\\conda.exe', 'run', '-n', 'pandrator_installer', 'pip', 'install', '-r', 'D:\\Pandrator\\Pandrator\\requirements.txt']' returned non-zero exit status 1.
`

**Comment by lukaszliniewicz** [comment]
You would have to install VoiceCraft first. And, to be honest, I don't  recommend it. What do you mean by burning subtitles? Adding the generated audio to the video?

**Comment by luckyluca** [comment]
Thanks, I'll skip VoiceCraft and use XTTS then. 

No, I meant to burn the .srt text over the video. Is that possible to do?

I ended up downloading the largest v25 package and using that as is.
It works great this way, except that subdud doesn't work. Everytime that is invoked from Pandrator, Pandrator hangs and after a while I get an error like this one below:
![Screenshot 2024-10-18 191314](https://github.com/user-attachments/assets/dce94908-b864-4f21-abe9-0100d3609db8)

**Comment by lukaszliniewicz** [comment]
Have you installed WhisperX or downloaded the package with it? What do the logs say when it errors out like this?

As for the quality of the voice, there are two things you can do - use RVC or fine-tune XTTS. For RVC, you have to find a model you like. If you want to fine-tune XTTS, collect at least 5m of good, clear speech (from one speaker, no music, as little noise as possible) and use the tool in Pandrator. Optimally, you'd use at least 30m. If you have an audiobook you like, or can find something on Librivox, for example, you can use that.

**Comment by luckyluca** [comment]
yes, I downloaded the biggest zip and extracted it. And using the installer_launcher exe to launch Pandrator with xtts selected.
It should be coming with whisperx and deepl already right?

I also uninstalled my local Python and any env reference to it.

With this extracted clean setup, transcribe and translate freeze pandrator.
Here's the log.

Are you sure I don't need any other dependencies or local python to run subdud / whisperx / deepl / pandrator?

[pandrator_20241019_130343.log](https://github.com/user-attachments/files/17444818/pandrator_20241019_130343.log)

**Comment by lukaszliniewicz** [comment]
The problem was that the 10 series cards do not support float16 computation. I added a check and now int8 should be used for these cards. Please update Pandrator from the launcher and try again.

**Comment by luckyluca** [comment]
Many thanks!
see [https://github.com/lukaszliniewicz/Pandrator/issues/54#issuecomment-2424166765](url)

**Comment by luckyluca** [comment]
I added api keys for deepL and Anthropic. 
Selecting deepL now translates correctly (yay!). Maybe it was failing before because I have no credits on Anthropic.

So, selecting any Anthropic models hangs Pandrator. Selecting deepL works.

Is there a way to run the translate/transcribe locally? I can see a local option as well, but it hangs Pandrator.
