### ISSUE TITLE
Environment location not found 

### ISSUE THREAD

**Issue by Bookwald** [lukaszliniewicz/Pandrator#6]
EnvironmentLocationNotFound: Not a conda environment: C:\Users\SayoPC\.conda\envs\pandrator_installer

I can successfully install with the one click installer but when running I get this error. How can I fix it?

**Comment by lukaszliniewicz** [comment]
What version of the installer have you used (xtts. silero... and .exe or .py)?

**Comment by Bookwald** [comment]
I ran voicecraft. At the time I had miniforge installed. Your one click installer installs miniconda3, which I believe cause an environmental variable conflict. I uninstalled both. Tried your installer on a clean Windows 11 on another computer and  it worked. Reinstalled Pandrator on the original PC and it's working now.
