### ISSUE TITLE
v.0.0.6 XTTS Generation works as it should but VoiceCraft has several issues

### ISSUE THREAD

**Issue by Bookwald** [lukaszliniewicz/Pandrator#7]
As of v.0.0.6, VoiceCraft produced audio that repeats lines and uses two voices. VoiceCraft also doesn't output all the sentences but rather the first few. Generation time is very long. I've seen it eat up 24GB VRAM and an additional 70GB RAM only to output 37 seconds of audio after 7 minutes of generation time.

Sample: https://sndup.net/v4x5/

**Comment by lukaszliniewicz** [comment]
Yes, VoiceCraft is far from perfect. Voice cloning is superior to XTTS, but it's not reliable. It's good for generating relatively short fragments and manually regenerating sentences until it produces something usable. I will expose more settings in the GUI, perhaps you can improve the results by playing with them. As for VRAM/RAM consumption and speed, I'm afraid I cannot do anything about it now. How many seconds of the sample were you using?

**Comment by lukaszliniewicz** [comment]
I can see they uploaded new TTS models yesterday, but I can't find the actual files. Will add them when I do. I should be able to expose the additional API settings in the GUI today. But I think for longer generations I'd recommend using XTTS with RVC for best voice cloning results.

**Comment by lukaszliniewicz** [comment]
I added the other parameters to the GUI under "Advanced settings". Please try disabling the cache (set the value from 1 to 0, it drastically reduced VRAM usage for me) and play a little with the others (try setting "stop repetition" to 2, for example, or possibly "sample batch size" to 2. I will update the API to use the newer models tomorrow.

**Comment by Bookwald** [comment]
Thanks for working on this. I'm looking forward to trying out the newer models. I'll test disabled cache and repetition.

**Comment by lukaszliniewicz** [comment]
I've added model selection to the GUI. Please try both the 330M model and the larger 830M model. Also, the cache is now cleared after every generation, which is something that I overlooked in the original code. Perhaps this will solve the issue with excessive VRAM usage.

**Comment by Bookwald** [comment]
With VoiceCraft I still had to disable cache to reduce VRAM usage. I'm getting a repeat of the first line of my reference audio at the beginning of each sentence of my input text. However, I'm finding XTTS to work excellent with RVC on top. XTTS captures the way the person speaks and RVC gives the texture of the voice back.

**Comment by lukaszliniewicz** [comment]
I tested it today on a rented vm with a 3090 and it used about 12GB of VRAM (with cache on). There were no instances of reference audio in the generations and generally the quality was quite good. Have you updated / reinstalled VoiceCraft API? Anyway, I'm glad that XTTS + RVC works well for you :)
