### ISSUE TITLE
On fedora 40 i got no file show on Select source file but if if type the path it works

### ISSUE THREAD

**Issue by yodatak** [lukaszliniewicz/Pandrator#9]
I thanks again i try to take a epub but i don't show on the file chooser but its work if i type the path maybe some issue with regex or something let me know if could help to debug 

![image](https://github.com/lukaszliniewicz/Pandrator/assets/704477/f58c6d02-6492-4286-9a61-2ea66e5203d6)

**Comment by yodatak** [comment]
An i think its unrelated but i got this error to when i try to generate 

Traceback (most recent call last):
  File "/usr/lib64/python3.12/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/var/home/yodatak/Projets/public/AI/Pandrator/panda_env/lib64/python3.12/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/var/home/yodatak/Projets/public/AI/Pandrator/pandrator.py", line 1359, in start_optimisation_thread
    preprocessed_sentences = self.preprocess_text(text)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/yodatak/Projets/public/AI/Pandrator/pandrator.py", line 1502, in preprocess_text
    for match in paragraph_breaks:
                 ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'paragraph_breaks' where it is not associated with a value

**Comment by lukaszliniewicz** [comment]
Sorry about that... I will investigate tomorrow. Was it an EPUB file? Do other file types work (txt, pdf)?

**Comment by yodatak** [comment]
It's for all files epub or txt

**Comment by lukaszliniewicz** [comment]
Please try it now. File selection should work and hopefully the error will be fixed.

**Comment by yodatak** [comment]
It work now and i can generate audio thanks !!! If you want some translation of your software in french or want some help to install on fedora i can help !

**Comment by lukaszliniewicz** [comment]
Thank you very much, you've helped me already!
